export const DOWNLOAD_PL_STARTED = 'DOWNLOAD_PRODUCT_LIST_STARTED';
export const DOWNLOAD_PL_SUCCESS = 'DOWNLOAD_PRODUCT_LIST_SUCCESS';
export const DOWNLOAD_PL_ERROR = 'DOWNLOAD_PRODUCT_LIST_ERROR';
